[package]
name = "regresstest"
edition.workspace = true
rust-version.workspace = true
description = "Regression testing"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
fern.workspace = true
fs-err.workspace = true
futures-util = { version = "0.3.28", default-features = false, features = ["std"] }
log.workspace = true
tokio = { version = "1.28.2", features = ["macros", "process", "rt", "time"] }
toollib = { path = "../toollib" }

[lints]
workspace = true
