[package]
name = "advent-of-code-2018-07b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 07b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["topological-sort", "tree"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
