[package]
name = "advent-of-code-2018-12b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2018, problem 12b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["cellular-automata"]

[dependencies]
adventutil = { path = "../../adventutil" }
itertools.workspace = true

[lints]
workspace = true
