[package]
name = "gen"
edition.workspace = true
rust-version.workspace = true
description = "Solution package generator"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
fs-err.workspace = true
serde.workspace = true
tinytemplate = "1.2.1"
toollib = { path = "../toollib" }

[lints]
workspace = true
