[package]
name = "advent-of-code-2021-15b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2021, problem 15b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }
