[package]
name = "advent-of-code-2025-08a"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2025, problem 08a"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory"]

[dependencies]
adventutil = { path = "../../adventutil" }
ordered-float.workspace = true

[lints]
workspace = true
