[package]
name = "advent-of-code-2025-01b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2025, problem 01b"
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
