[package]
name = "advent-of-code-2019-15b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2019, problem 15b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["maze", "intcode", "grid-movement", "flood-fill"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
