[package]
name = "advent-of-code-2025-08b"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2025, problem 08b"
authors.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["graph-theory", "taxicab-metric"]

[dependencies]
adventutil = { path = "../../adventutil" }
ordered-float.workspace = true

[lints]
workspace = true
