[package]
name = "advent-of-code-2023-17a"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
description = "Solution to Advent of Code 2023, problem 17a"
authors.workspace = true
repository.workspace = true
license.workspace = true
publish.workspace = true
keywords = ["grid-movement", "optimization", "shortest-path"]

[dependencies]
adventutil = { path = "../../adventutil" }

[lints]
workspace = true
